### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by otymartin** [maail/MMSlidingButton#3]
@maail 

Hi thanks for the lib. Unfortunately its unusable in a swift 3 project.

Could you make it swift 3 compatible?

thanks

**Comment by joaotocilo** [comment]
Hi @otymartin , I sent a pull request with this update, let's wait.

See ya.

**Comment by otymartin** [comment]
@joaotocilo nice thanks :)

**Comment by maail** [comment]
@joaotocilo nice work. thanks! 
@otymartin sorry was going to get to it soon. But glad @joaotocilo did.
